Background:

I have chosen to begin this “book” at the time that Moshe received the Torah from Mount Sinai. As such, it is important that I preface this section by choosing/assigning the starting point and describing the discrepancies between traditional Jewish chronology that was derived through rabbinical interpretation (counting the days forward, beginning at the creation of the world at the year zero, or 3760 BCE) and historical sources (which tend to count dates backwards, relative to the present). 

Jewish tradition counts all dates with respect to the creation of the world, which is said to have occurred in the year zero, or 3760 BCE. The Seder Olam Rabbah, a 2nd-century CE Jewish text provides a chronology of biblical events and is often referred to when pinpointing Jewish chronology. Traditional sources pose that Moshe received the Torah on the same year in the third month of the Exodus from Egypt [Exodus 19:1], during the year 2448 of the Hebrew calendar (1312 BCE assuming no year zero between BCE and CE). 

Secular scholarship works with the Gregorian calendar and uses archaeological and historical evidence to determine dating. Many scholars doubt the authenticity of the Exodus, suggesting that some interpretations are mystical and exaggerated, and that biblical timelines are inaccurate. Modern studies of Egyptian history and the ancient Near East suggest that interactions between Egypt and the Levant that are described by the Exodus might have more likely aligned with historical interpretations during the late 13th or early 12th centuries BCE.

For the purpose of this work, and in terms of the context that I will try to provide by giving a top-down approach to Jewish history, we will use the date of 1312 BCE as a starting point, because, quite frankly, I’m an observant yid and have no better reason to choose any other arbitrary place to start.
